const riders = [
  {
    id: 1,
    name: "POGAČAR Tadej ",
    team: "UAE Team Emirates",
    inCourse: true,
    shirt: "shirts\\uae-team-emirates-xrg-2025.png",
  },
  {
    id: 2,
    name: "ALMEIDA João ",
    team: "UAE Team Emirates",
    inCourse: false,
    shirt: "shirts\\uae-team-emirates-xrg-2025.png",
  },
  {
    id: 3,
    name: "NARVÁEZ Jhonatan ",
    team: "UAE Team Emirates",
    inCourse: true,
    shirt: "shirts\\uae-team-emirates-xrg-2025.png",
  },
  {
    id: 4,
    name: "POLITT Nils ",
    team: "UAE Team Emirates",
    inCourse: true,
    shirt: "shirts\\uae-team-emirates-xrg-2025.png",
  },
  {
    id: 5,
    name: "SIVAKOV Pavel ",
    team: "UAE Team Emirates",
    inCourse: true,
    shirt: "shirts\\uae-team-emirates-xrg-2025.png",
  },
  {
    id: 6,
    name: "SOLER Marc ",
    team: "UAE Team Emirates",
    inCourse: true,
    shirt: "shirts\\uae-team-emirates-xrg-2025.png",
  },
  {
    id: 7,
    name: "WELLENS Tim ",
    team: "UAE Team Emirates",
    inCourse: true,
    shirt: "shirts\\uae-team-emirates-xrg-2025.png",
  },
  {
    id: 8,
    name: "YATES Adam ",
    team: "UAE Team Emirates",
    inCourse: true,
    shirt: "shirts\\uae-team-emirates-xrg-2025.png",
  },
  {
    id: 11,
    name: "VINGEGAARD Jonas ",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\team-visma-lease-a-bike-2025-n2.png",
  },
  {
    id: 12,
    name: "AFFINI Edoardo ",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\team-visma-lease-a-bike-2025-n2.png",
  },
  {
    id: 13,
    name: "BENOOT Tiesj ",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\team-visma-lease-a-bike-2025-n2.png",
  },
  {
    id: 14,
    name: "CAMPENAERTS Victor ",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\team-visma-lease-a-bike-2025-n2.png",
  },
  {
    id: 15,
    name: "JORGENSON Matteo ",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\team-visma-lease-a-bike-2025-n2.png",
  },
  {
    id: 16,
    name: "KUSS Sepp ",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\team-visma-lease-a-bike-2025-n2.png",
  },
  {
    id: 17,
    name: "VAN AERT Wout ",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\team-visma-lease-a-bike-2025-n2.png",
  },
  {
    id: 18,
    name: "YATES Simon ",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\team-visma-lease-a-bike-2025-n2.png",
  },
  {
    id: 21,
    name: "EVENEPOEL Remco ",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\soudal-quick-step-2025.png",
  },
  {
    id: 22,
    name: "CATTANEO Mattia ",
    team: "Soudal Quick-Step",
    inCourse: false,
    shirt: "shirts\\soudal-quick-step-2025.png",
  },
  {
    id: 23,
    name: "EENKHOORN Pascal ",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\soudal-quick-step-2025.png",
  },
  {
    id: 24,
    name: "MERLIER Tim ",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\soudal-quick-step-2025.png",
  },
  {
    id: 25,
    name: "PARET-PEINTRE Valentin ",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\soudal-quick-step-2025.png",
  },
  {
    id: 26,
    name: "SCHACHMANN Maximilian ",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\soudal-quick-step-2025.png",
  },
  {
    id: 27,
    name: "VAN LERBERGHE Bert ",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\soudal-quick-step-2025.png",
  },
  {
    id: 28,
    name: "VAN WILDER Ilan ",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\soudal-quick-step-2025.png",
  },
  {
    id: 31,
    name: "HEALY Ben ",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\ef-education-easypost-2025.png",
  },
  {
    id: 32,
    name: "ALBANESE Vincenzo ",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\ef-education-easypost-2025.png",
  },
  {
    id: 33,
    name: "ASGREEN Kasper ",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\ef-education-easypost-2025.png",
  },
  {
    id: 34,
    name: "BAUDIN Alex ",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\ef-education-easypost-2025.png",
  },
  {
    id: 35,
    name: "POWLESS Neilson ",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\ef-education-easypost-2025.png",
  },
  {
    id: 36,
    name: "SWEENY Harry ",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\ef-education-easypost-2025.png",
  },
  {
    id: 37,
    name: "VALGREN Michael ",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\ef-education-easypost-2025.png",
  },
  {
    id: 38,
    name: "VAN DEN BERG Marijn ",
    team: "EF Education - EasyPost",
    inCourse: false,
    shirt: "shirts\\ef-education-easypost-2025.png",
  },
  {
    id: 41,
    name: "GIRMAY Biniam ",
    team: "Intermarché - Wanty",
    inCourse: true,
    shirt: "shirts\\intermarche-wanty-2025-n2.png",
  },
  {
    id: 42,
    name: "BARRÉ Louis ",
    team: "Intermarché - Wanty",
    inCourse: true,
    shirt: "shirts\\intermarche-wanty-2025-n2.png",
  },
  {
    id: 43,
    name: "BRAET Vito ",
    team: "Intermarché - Wanty",
    inCourse: true,
    shirt: "shirts\\intermarche-wanty-2025-n2.png",
  },
  {
    id: 44,
    name: "PAGE Hugo ",
    team: "Intermarché - Wanty",
    inCourse: true,
    shirt: "shirts\\intermarche-wanty-2025-n2.png",
  },
  {
    id: 45,
    name: "REX Laurenz ",
    team: "Intermarché - Wanty",
    inCourse: true,
    shirt: "shirts\\intermarche-wanty-2025-n2.png",
  },
  {
    id: 46,
    name: "RUTSCH Jonas ",
    team: "Intermarché - Wanty",
    inCourse: true,
    shirt: "shirts\\intermarche-wanty-2025-n2.png",
  },
  {
    id: 47,
    name: "VAN SINTMAARTENSDIJK Roel ",
    team: "Intermarché - Wanty",
    inCourse: true,
    shirt: "shirts\\intermarche-wanty-2025-n2.png",
  },
  {
    id: 48,
    name: "ZIMMERMANN Georg ",
    team: "Intermarché - Wanty",
    inCourse: false,
    shirt: "shirts\\intermarche-wanty-2025-n2.png",
  },
  {
    id: 51,
    name: "BUITRAGO Santiago ",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\bahrain-victorious-2025-n2.png",
  },
  {
    id: 52,
    name: "BAUHAUS Phil ",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\bahrain-victorious-2025-n2.png",
  },
  {
    id: 53,
    name: "GRADEK Kamil ",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\bahrain-victorious-2025-n2.png",
  },
  {
    id: 54,
    name: "HAIG Jack ",
    team: "Bahrain - Victorious",
    inCourse: false,
    shirt: "shirts\\bahrain-victorious-2025-n2.png",
  },
  {
    id: 55,
    name: "MARTINEZ Lenny ",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\bahrain-victorious-2025-n2.png",
  },
  {
    id: 56,
    name: "MOHORIČ Matej ",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\bahrain-victorious-2025-n2.png",
  },
  {
    id: 57,
    name: "STANNARD Robert ",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\bahrain-victorious-2025-n2.png",
  },
  {
    id: 58,
    name: "WRIGHT Fred ",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\bahrain-victorious-2025-n2.png",
  },
  {
    id: 61,
    name: "THOMAS Geraint ",
    team: "INEOS Grenadiers",
    inCourse: true,
    shirt: "shirts\\ineos-grenadiers-2025.png",
  },
  {
    id: 62,
    name: "ARENSMAN Thymen ",
    team: "INEOS Grenadiers",
    inCourse: true,
    shirt: "shirts\\ineos-grenadiers-2025.png",
  },
  {
    id: 63,
    name: "FOSS Tobias ",
    team: "INEOS Grenadiers",
    inCourse: true,
    shirt: "shirts\\ineos-grenadiers-2025.png",
  },
  {
    id: 64,
    name: "GANNA Filippo ",
    team: "INEOS Grenadiers",
    inCourse: false,
    shirt: "shirts\\ineos-grenadiers-2025.png",
  },
  {
    id: 65,
    name: "LAURANCE Axel ",
    team: "INEOS Grenadiers",
    inCourse: true,
    shirt: "shirts\\ineos-grenadiers-2025.png",
  },
  {
    id: 66,
    name: "RODRÍGUEZ Carlos ",
    team: "INEOS Grenadiers",
    inCourse: true,
    shirt: "shirts\\ineos-grenadiers-2025.png",
  },
  {
    id: 67,
    name: "SWIFT Connor ",
    team: "INEOS Grenadiers",
    inCourse: true,
    shirt: "shirts\\ineos-grenadiers-2025.png",
  },
  {
    id: 68,
    name: "WATSON Samuel ",
    team: "INEOS Grenadiers",
    inCourse: true,
    shirt: "shirts\\ineos-grenadiers-2025.png",
  },
  {
    id: 71,
    name: "ROGLIČ Primož ",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\red-bull-bora-hansgrohe-2025.png",
  },
  {
    id: 72,
    name: "LIPOWITZ Florian ",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\red-bull-bora-hansgrohe-2025.png",
  },
  {
    id: 73,
    name: "MEEUS Jordi ",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\red-bull-bora-hansgrohe-2025.png",
  },
  {
    id: 74,
    name: "MOSCON Gianni ",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\red-bull-bora-hansgrohe-2025.png",
  },
  {
    id: 75,
    name: "PITHIE Laurence ",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\red-bull-bora-hansgrohe-2025.png",
  },
  {
    id: 76,
    name: "VAN DIJKE Mick ",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\red-bull-bora-hansgrohe-2025.png",
  },
  {
    id: 77,
    name: "VAN POPPEL Danny ",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\red-bull-bora-hansgrohe-2025.png",
  },
  {
    id: 78,
    name: "VLASOV Aleksandr ",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\red-bull-bora-hansgrohe-2025.png",
  },
  {
    id: 81,
    name: "MILAN Jonathan ",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\lidl-trek-2025-n2.png",
  },
  {
    id: 82,
    name: "CONSONNI Simone ",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\lidl-trek-2025-n2.png",
  },
  {
    id: 83,
    name: "NYS Thibau ",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\lidl-trek-2025-n2.png",
  },
  {
    id: 84,
    name: "SIMMONS Quinn ",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\lidl-trek-2025-n2.png",
  },
  {
    id: 85,
    name: "SKJELMOSE Mattias ",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\lidl-trek-2025-n2.png",
  },
  {
    id: 86,
    name: "SKUJIŅŠ Toms ",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\lidl-trek-2025-n2.png",
  },
  {
    id: 87,
    name: "STUYVEN Jasper ",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\lidl-trek-2025-n2.png",
  },
  {
    id: 88,
    name: "THEUNS Edward ",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\lidl-trek-2025-n2.png",
  },
  {
    id: 91,
    name: "MARTIN Guillaume ",
    team: "Groupama - FDJ",
    inCourse: true,
    shirt: "shirts\\groupama-fdj-2025.png",
  },
  {
    id: 92,
    name: "ASKEY Lewis ",
    team: "Groupama - FDJ",
    inCourse: true,
    shirt: "shirts\\groupama-fdj-2025.png",
  },
  {
    id: 93,
    name: "BARTHE Cyril ",
    team: "Groupama - FDJ",
    inCourse: true,
    shirt: "shirts\\groupama-fdj-2025.png",
  },
  {
    id: 94,
    name: "GRÉGOIRE Romain ",
    team: "Groupama - FDJ",
    inCourse: true,
    shirt: "shirts\\groupama-fdj-2025.png",
  },
  {
    id: 95,
    name: "MADOUAS Valentin ",
    team: "Groupama - FDJ",
    inCourse: true,
    shirt: "shirts\\groupama-fdj-2025.png",
  },
  {
    id: 96,
    name: "PACHER Quentin ",
    team: "Groupama - FDJ",
    inCourse: true,
    shirt: "shirts\\groupama-fdj-2025.png",
  },
  {
    id: 97,
    name: "PENHOËT Paul ",
    team: "Groupama - FDJ",
    inCourse: true,
    shirt: "shirts\\groupama-fdj-2025.png",
  },
  {
    id: 98,
    name: "RUSSO Clément ",
    team: "Groupama - FDJ",
    inCourse: true,
    shirt: "shirts\\groupama-fdj-2025.png",
  },
  {
    id: 101,
    name: "PHILIPSEN Jasper ",
    team: "Alpecin - Deceuninck",
    inCourse: false,
    shirt: "shirts\\alpecin-deceuninck-2025-n2.png",
  },
  {
    id: 102,
    name: "DILLIER Silvan ",
    team: "Alpecin - Deceuninck",
    inCourse: true,
    shirt: "shirts\\alpecin-deceuninck-2025-n2.png",
  },
  {
    id: 103,
    name: "GROVES Kaden ",
    team: "Alpecin - Deceuninck",
    inCourse: true,
    shirt: "shirts\\alpecin-deceuninck-2025-n2.png",
  },
  {
    id: 104,
    name: "MEURISSE Xandro ",
    team: "Alpecin - Deceuninck",
    inCourse: true,
    shirt: "shirts\\alpecin-deceuninck-2025-n2.png",
  },
  {
    id: 105,
    name: "RICKAERT Jonas ",
    team: "Alpecin - Deceuninck",
    inCourse: true,
    shirt: "shirts\\alpecin-deceuninck-2025-n2.png",
  },
  {
    id: 106,
    name: "VAN DER POEL Mathieu ",
    team: "Alpecin - Deceuninck",
    inCourse: true,
    shirt: "shirts\\alpecin-deceuninck-2025-n2.png",
  },
  {
    id: 107,
    name: "VERMEERSCH Gianni ",
    team: "Alpecin - Deceuninck",
    inCourse: true,
    shirt: "shirts\\alpecin-deceuninck-2025-n2.png",
  },
  {
    id: 108,
    name: "VERSTRYNGE Emiel ",
    team: "Alpecin - Deceuninck",
    inCourse: true,
    shirt: "shirts\\alpecin-deceuninck-2025-n2.png",
  },
  {
    id: 111,
    name: "ALAPHILIPPE Julian ",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\tudor-pro-cycling-team-2025.png",
  },
  {
    id: 112,
    name: "DAINESE Alberto ",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\tudor-pro-cycling-team-2025.png",
  },
  {
    id: 113,
    name: "HALLER Marco ",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\tudor-pro-cycling-team-2025.png",
  },
  {
    id: 114,
    name: "HIRSCHI Marc ",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\tudor-pro-cycling-team-2025.png",
  },
  {
    id: 115,
    name: "LIENHARD Fabian ",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\tudor-pro-cycling-team-2025.png",
  },
  {
    id: 116,
    name: "MAYRHOFER Marius ",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\tudor-pro-cycling-team-2025.png",
  },
  {
    id: 117,
    name: "STORER Michael ",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\tudor-pro-cycling-team-2025.png",
  },
  {
    id: 118,
    name: "TRENTIN Matteo ",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\tudor-pro-cycling-team-2025.png",
  },
  {
    id: 121,
    name: "O'CONNOR Ben ",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\team-jayco-alula-2025.png",
  },
  {
    id: 122,
    name: "DUNBAR Eddie ",
    team: "Team Jayco AlUla",
    inCourse: false,
    shirt: "shirts\\team-jayco-alula-2025.png",
  },
  {
    id: 123,
    name: "DURBRIDGE Luke ",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\team-jayco-alula-2025.png",
  },
  {
    id: 124,
    name: "GROENEWEGEN Dylan ",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\team-jayco-alula-2025.png",
  },
  {
    id: 125,
    name: "MEZGEC Luka ",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\team-jayco-alula-2025.png",
  },
  {
    id: 126,
    name: "PLAPP Luke ",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\team-jayco-alula-2025.png",
  },
  {
    id: 127,
    name: "REINDERS Elmar ",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\team-jayco-alula-2025.png",
  },
  {
    id: 128,
    name: "SCHMID Mauro ",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\team-jayco-alula-2025.png",
  },
  {
    id: 131,
    name: "VAUQUELIN Kévin ",
    team: "Arkéa - B&B Hotels",
    inCourse: true,
    shirt: "shirts\\arkea-b-b-hotels-2025.png",
  },
  {
    id: 132,
    name: "CAPIOT Amaury ",
    team: "Arkéa - B&B Hotels",
    inCourse: true,
    shirt: "shirts\\arkea-b-b-hotels-2025.png",
  },
  {
    id: 133,
    name: "COSTIOU Ewen ",
    team: "Arkéa - B&B Hotels",
    inCourse: true,
    shirt: "shirts\\arkea-b-b-hotels-2025.png",
  },
  {
    id: 134,
    name: "DÉMARE Arnaud ",
    team: "Arkéa - B&B Hotels",
    inCourse: true,
    shirt: "shirts\\arkea-b-b-hotels-2025.png",
  },
  {
    id: 135,
    name: "GARCÍA PIERNA Raúl ",
    team: "Arkéa - B&B Hotels",
    inCourse: true,
    shirt: "shirts\\arkea-b-b-hotels-2025.png",
  },
  {
    id: 136,
    name: "LE BERRE Mathis ",
    team: "Arkéa - B&B Hotels",
    inCourse: true,
    shirt: "shirts\\arkea-b-b-hotels-2025.png",
  },
  {
    id: 137,
    name: "RODRÍGUEZ Cristián ",
    team: "Arkéa - B&B Hotels",
    inCourse: true,
    shirt: "shirts\\arkea-b-b-hotels-2025.png",
  },
  {
    id: 138,
    name: "VENTURINI Clément ",
    team: "Arkéa - B&B Hotels",
    inCourse: true,
    shirt: "shirts\\arkea-b-b-hotels-2025.png",
  },
  {
    id: 141,
    name: "MAS Enric ",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\movistar-team-2025-n2.png",
  },
  {
    id: 142,
    name: "BARTA Will ",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\movistar-team-2025-n2.png",
  },
  {
    id: 143,
    name: "CASTRILLO Pablo ",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\movistar-team-2025-n2.png",
  },
  {
    id: 144,
    name: "OLIVEIRA Nelson ",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\movistar-team-2025-n2.png",
  },
  {
    id: 145,
    name: "GARCÍA CORTINA Iván ",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\movistar-team-2025-n2.png",
  },
  {
    id: 146,
    name: "MÜHLBERGER Gregor ",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\movistar-team-2025-n2.png",
  },
  {
    id: 147,
    name: "ROMEO Iván ",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\movistar-team-2025-n2.png",
  },
  {
    id: 148,
    name: "RUBIO Einer ",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\movistar-team-2025-n2.png",
  },
  {
    id: 151,
    name: "GALL Felix ",
    team: "Decathlon AG2R La Mondiale Team",
    inCourse: true,
    shirt: "shirts\\decathlon-ag2r-la-mondiale-2025.png",
  },
  {
    id: 152,
    name: "ARMIRAIL Bruno ",
    team: "Decathlon AG2R La Mondiale Team",
    inCourse: true,
    shirt: "shirts\\decathlon-ag2r-la-mondiale-2025.png",
  },
  {
    id: 153,
    name: "BERTHET Clément ",
    team: "Decathlon AG2R La Mondiale Team",
    inCourse: true,
    shirt: "shirts\\decathlon-ag2r-la-mondiale-2025.png",
  },
  {
    id: 154,
    name: "BISSEGGER Stefan ",
    team: "Decathlon AG2R La Mondiale Team",
    inCourse: false,
    shirt: "shirts\\decathlon-ag2r-la-mondiale-2025.png",
  },
  {
    id: 155,
    name: "NAESEN Oliver ",
    team: "Decathlon AG2R La Mondiale Team",
    inCourse: true,
    shirt: "shirts\\decathlon-ag2r-la-mondiale-2025.png",
  },
  {
    id: 156,
    name: "PARET-PEINTRE Aurélien ",
    team: "Decathlon AG2R La Mondiale Team",
    inCourse: true,
    shirt: "shirts\\decathlon-ag2r-la-mondiale-2025.png",
  },
  {
    id: 157,
    name: "SCOTSON Callum ",
    team: "Decathlon AG2R La Mondiale Team",
    inCourse: true,
    shirt: "shirts\\decathlon-ag2r-la-mondiale-2025.png",
  },
  {
    id: 158,
    name: "TRONCHON Bastien ",
    team: "Decathlon AG2R La Mondiale Team",
    inCourse: true,
    shirt: "shirts\\decathlon-ag2r-la-mondiale-2025.png",
  },
  {
    id: 161,
    name: "BUCHMANN Emanuel ",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\cofidis-2025-n4.png",
  },
  {
    id: 162,
    name: "ARANBURU Alex ",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\cofidis-2025-n4.png",
  },
  {
    id: 163,
    name: "COQUARD Bryan ",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\cofidis-2025-n4.png",
  },
  {
    id: 164,
    name: "IZAGIRRE Ion ",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\cofidis-2025-n4.png",
  },
  {
    id: 165,
    name: "RENARD Alexis ",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\cofidis-2025-n4.png",
  },
  {
    id: 166,
    name: "TEUNS Dylan ",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\cofidis-2025-n4.png",
  },
  {
    id: 167,
    name: "THOMAS Benjamin ",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\cofidis-2025-n4.png",
  },
  {
    id: 168,
    name: "TOUZÉ Damien ",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\cofidis-2025-n4.png",
  },
  {
    id: 171,
    name: "TEJADA Harold ",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\xds-astana-team-2025.png",
  },
  {
    id: 172,
    name: "BALLERINI Davide ",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\xds-astana-team-2025.png",
  },
  {
    id: 173,
    name: "BOL Cees ",
    team: "XDS Astana Team",
    inCourse: false,
    shirt: "shirts\\xds-astana-team-2025.png",
  },
  {
    id: 174,
    name: "CHAMPOUSSIN Clément ",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\xds-astana-team-2025.png",
  },
  {
    id: 175,
    name: "FEDOROV Yevgeniy ",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\xds-astana-team-2025.png",
  },
  {
    id: 176,
    name: "HIGUITA Sergio ",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\xds-astana-team-2025.png",
  },
  {
    id: 177,
    name: "TEUNISSEN Mike ",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\xds-astana-team-2025.png",
  },
  {
    id: 178,
    name: "VELASCO Simone ",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\xds-astana-team-2025.png",
  },
  {
    id: 181,
    name: "CRAS Steff ",
    team: "Team TotalEnergies",
    inCourse: true,
    shirt: "shirts\\totalenergies-2025.png",
  },
  {
    id: 182,
    name: "BURGAUDEAU Mathieu ",
    team: "Team TotalEnergies",
    inCourse: true,
    shirt: "shirts\\totalenergies-2025.png",
  },
  {
    id: 183,
    name: "DELETTRE Alexandre ",
    team: "Team TotalEnergies",
    inCourse: true,
    shirt: "shirts\\totalenergies-2025.png",
  },
  {
    id: 184,
    name: "GACHIGNARD Thomas ",
    team: "Team TotalEnergies",
    inCourse: true,
    shirt: "shirts\\totalenergies-2025.png",
  },
  {
    id: 185,
    name: "JEANNIÈRE Emilien ",
    team: "Team TotalEnergies",
    inCourse: false,
    shirt: "shirts\\totalenergies-2025.png",
  },
  {
    id: 186,
    name: "JEGAT Jordan ",
    team: "Team TotalEnergies",
    inCourse: true,
    shirt: "shirts\\totalenergies-2025.png",
  },
  {
    id: 187,
    name: "TURGIS Anthony ",
    team: "Team TotalEnergies",
    inCourse: true,
    shirt: "shirts\\totalenergies-2025.png",
  },
  {
    id: 188,
    name: "VERCHER Mattéo ",
    team: "Team TotalEnergies",
    inCourse: true,
    shirt: "shirts\\totalenergies-2025.png",
  },
  {
    id: 191,
    name: "ONLEY Oscar ",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\team-picnic-postnl-2025.png",
  },
  {
    id: 192,
    name: "BARGUIL Warren ",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\team-picnic-postnl-2025.png",
  },
  {
    id: 193,
    name: "BITTNER Pavel ",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\team-picnic-postnl-2025.png",
  },
  {
    id: 194,
    name: "FLYNN Sean ",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\team-picnic-postnl-2025.png",
  },
  {
    id: 195,
    name: "ANDRESEN Tobias Lund ",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\team-picnic-postnl-2025.png",
  },
  {
    id: 196,
    name: "MÄRKL Niklas ",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\team-picnic-postnl-2025.png",
  },
  {
    id: 197,
    name: "NABERMAN Tim ",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\team-picnic-postnl-2025.png",
  },
  {
    id: 198,
    name: "VAN DEN BROEK Frank ",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\team-picnic-postnl-2025.png",
  },
  {
    id: 201,
    name: "WOODS Michael ",
    team: "Israel - Premier Tech",
    inCourse: true,
    shirt: "shirts\\israel-premier-tech-2025.png",
  },
  {
    id: 202,
    name: "ACKERMANN Pascal ",
    team: "Israel - Premier Tech",
    inCourse: true,
    shirt: "shirts\\israel-premier-tech-2025.png",
  },
  {
    id: 203,
    name: "BLACKMORE Joseph ",
    team: "Israel - Premier Tech",
    inCourse: true,
    shirt: "shirts\\israel-premier-tech-2025.png",
  },
  {
    id: 204,
    name: "BOIVIN Guillaume ",
    team: "Israel - Premier Tech",
    inCourse: true,
    shirt: "shirts\\israel-premier-tech-2025.png",
  },
  {
    id: 205,
    name: "LOUVEL Matis ",
    team: "Israel - Premier Tech",
    inCourse: true,
    shirt: "shirts\\israel-premier-tech-2025.png",
  },
  {
    id: 206,
    name: "LUTSENKO Alexey ",
    team: "Israel - Premier Tech",
    inCourse: true,
    shirt: "shirts\\israel-premier-tech-2025.png",
  },
  {
    id: 207,
    name: "NEILANDS Krists ",
    team: "Israel - Premier Tech",
    inCourse: true,
    shirt: "shirts\\israel-premier-tech-2025.png",
  },
  {
    id: 208,
    name: "STEWART Jake ",
    team: "Israel - Premier Tech",
    inCourse: true,
    shirt: "shirts\\israel-premier-tech-2025.png",
  },
  {
    id: 211,
    name: "DE LIE Arnaud ",
    team: "Lotto",
    inCourse: true,
    shirt: "shirts\\lotto-2025-n2.png",
  },
  {
    id: 212,
    name: "BERCKMOES Jenno ",
    team: "Lotto",
    inCourse: true,
    shirt: "shirts\\lotto-2025-n2.png",
  },
  {
    id: 213,
    name: "DE BUYST Jasper ",
    team: "Lotto",
    inCourse: false,
    shirt: "shirts\\lotto-2025-n2.png",
  },
  {
    id: 214,
    name: "DRIZNERS Jarrad ",
    team: "Lotto",
    inCourse: true,
    shirt: "shirts\\lotto-2025-n2.png",
  },
  {
    id: 215,
    name: "GRIGNARD Sébastien ",
    team: "Lotto",
    inCourse: true,
    shirt: "shirts\\lotto-2025-n2.png",
  },
  {
    id: 216,
    name: "SEPÚLVEDA Eduardo ",
    team: "Lotto",
    inCourse: true,
    shirt: "shirts\\lotto-2025-n2.png",
  },
  {
    id: 217,
    name: "VAN EETVELT Lennert ",
    team: "Lotto",
    inCourse: true,
    shirt: "shirts\\lotto-2025-n2.png",
  },
  {
    id: 218,
    name: "VAN MOER Brent ",
    team: "Lotto",
    inCourse: true,
    shirt: "shirts\\lotto-2025-n2.png",
  },
  {
    id: 221,
    name: "JOHANNESSEN Tobias Halland ",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\uno-x-mobility-2025.png",
  },
  {
    id: 222,
    name: "ABRAHAMSEN Jonas ",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\uno-x-mobility-2025.png",
  },
  {
    id: 223,
    name: "CORT Magnus ",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\uno-x-mobility-2025.png",
  },
  {
    id: 224,
    name: "FREDHEIM Stian ",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\uno-x-mobility-2025.png",
  },
  {
    id: 225,
    name: "HOELGAARD Markus ",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\uno-x-mobility-2025.png",
  },
  {
    id: 226,
    name: "JOHANNESSEN Anders Halland ",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\uno-x-mobility-2025.png",
  },
  {
    id: 227,
    name: "LEKNESSUND Andreas ",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\uno-x-mobility-2025.png",
  },
  {
    id: 228,
    name: "WÆRENSKJOLD Søren ",
    team: "Uno-X Mobility",
    inCourse: false,
    shirt: "shirts\\uno-x-mobility-2025.png",
  },
];
