// Complete lijst renners met rugnummers.

const riders = [
  {
    id: 1,
    name: "POGACAR Tadej",
    team: "UAE Team Emirates - XRG",
    inCourse: true,
    shirt: "shirts\\2026\\uae-team-emirates-xrg-2026.png",
  },
  {
    id: 2,
    name: "DEL TORO Isaac",
    team: "UAE Team Emirates - XRG",
    inCourse: true,
    shirt: "shirts\\2026\\uae-team-emirates-xrg-2026.png",
  },
  {
    id: 3,
    name: "WELLENS Tim",
    team: "UAE Team Emirates - XRG",
    inCourse: true,
    shirt: "shirts\\2026\\uae-team-emirates-xrg-2026.png",
  },
  {
    id: 4,
    name: "MCNULTY Brandon",
    team: "UAE Team Emirates - XRG",
    inCourse: true,
    shirt: "shirts\\2026\\uae-team-emirates-xrg-2026.png",
  },
  {
    id: 5,
    name: "YATES Adam",
    team: "UAE Team Emirates - XRG",
    inCourse: true,
    shirt: "shirts\\2026\\uae-team-emirates-xrg-2026.png",
  },
  {
    id: 6,
    name: "VERMEERSCH Florian",
    team: "UAE Team Emirates - XRG",
    inCourse: true,
    shirt: "shirts\\2026\\uae-team-emirates-xrg-2026.png",
  },
  {
    id: 7,
    name: "POLITT Nils",
    team: "UAE Team Emirates - XRG",
    inCourse: true,
    shirt: "shirts\\2026\\uae-team-emirates-xrg-2026.png",
  },
  {
    id: 8,
    name: "GROssSCHARTNER Felix",
    team: "UAE Team Emirates - XRG",
    inCourse: true,
    shirt: "shirts\\2026\\uae-team-emirates-xrg-2026.png",
  },
  {
    id: 9,
    name: "PHILIPSEN Jasper",
    team: "Alpecin - Premier Tech",
    inCourse: true,
    shirt: "shirts\\2026\\alpecin-premier-tech-2026.png",
  },
  {
    id: 10,
    name: "VAN DER POEL Mathieu",
    team: "Alpecin - Premier Tech",
    inCourse: true,
    shirt: "shirts\\2026\\alpecin-premier-tech-2026.png",
  },
  {
    id: 11,
    name: "VERSTRYNGE Emiel",
    team: "Alpecin - Premier Tech",
    inCourse: true,
    shirt: "shirts\\2026\\alpecin-premier-tech-2026.png",
  },
  {
    id: 12,
    name: "RICKAERT Jonas",
    team: "Alpecin - Premier Tech",
    inCourse: true,
    shirt: "shirts\\2026\\alpecin-premier-tech-2026.png",
  },
  {
    id: 13,
    name: "MARSMAN Tim",
    team: "Alpecin - Premier Tech",
    inCourse: true,
    shirt: "shirts\\2026\\alpecin-premier-tech-2026.png",
  },
  {
    id: 14,
    name: "DEBRUYNE Ramses",
    team: "Alpecin - Premier Tech",
    inCourse: true,
    shirt: "shirts\\2026\\alpecin-premier-tech-2026.png",
  },
  {
    id: 15,
    name: "PLANCKAERT Edward",
    team: "Alpecin - Premier Tech",
    inCourse: true,
    shirt: "shirts\\2026\\alpecin-premier-tech-2026.png",
  },
  {
    id: 16,
    name: "DILLIER Silvan",
    team: "Alpecin - Premier Tech",
    inCourse: true,
    shirt: "shirts\\2026\\alpecin-premier-tech-2026.png",
  },
  {
    id: 17,
    name: "TIBERI Antonio",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\2026\\bahrain-victorious-2026.png",
  },
  {
    id: 18,
    name: "MARTINEZ Lenny",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\2026\\bahrain-victorious-2026.png",
  },
  {
    id: 19,
    name: "MOHORIC Matej",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\2026\\bahrain-victorious-2026.png",
  },
  {
    id: 20,
    name: "BAUHAUS Phil",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\2026\\bahrain-victorious-2026.png",
  },
  {
    id: 21,
    name: "CARUSO Damiano",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\2026\\bahrain-victorious-2026.png",
  },
  {
    id: 22,
    name: "GRADEK Kamil",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\2026\\bahrain-victorious-2026.png",
  },
  {
    id: 23,
    name: "STANNARD Robert",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\2026\\bahrain-victorious-2026.png",
  },
  {
    id: 24,
    name: "VAN MECHELEN Vlad",
    team: "Bahrain - Victorious",
    inCourse: true,
    shirt: "shirts\\2026\\bahrain-victorious-2026.png",
  },
  {
    id: 25,
    name: "SEIXAS Paul",
    team: "Decathlon CMA CGM Team",
    inCourse: true,
    shirt: "shirts\\2026\\decathlon-cma-cgm-team-2026-n2.png",
  },
  {
    id: 26,
    name: "KOOIJ Olav",
    team: "Decathlon CMA CGM Team",
    inCourse: true,
    shirt: "shirts\\2026\\decathlon-cma-cgm-team-2026-n2.png",
  },
  {
    id: 27,
    name: "RICCITELLO Matthew",
    team: "Decathlon CMA CGM Team",
    inCourse: true,
    shirt: "shirts\\2026\\decathlon-cma-cgm-team-2026-n2.png",
  },
  {
    id: 28,
    name: "BENOOT Tiesj",
    team: "Decathlon CMA CGM Team",
    inCourse: true,
    shirt: "shirts\\2026\\decathlon-cma-cgm-team-2026-n2.png",
  },
  {
    id: 29,
    name: "HOOLE Daan",
    team: "Decathlon CMA CGM Team",
    inCourse: true,
    shirt: "shirts\\2026\\decathlon-cma-cgm-team-2026-n2.png",
  },
  {
    id: 30,
    name: "PRODHOMME Nicolas",
    team: "Decathlon CMA CGM Team",
    inCourse: true,
    shirt: "shirts\\2026\\decathlon-cma-cgm-team-2026-n2.png",
  },
  {
    id: 31,
    name: "PARET-PEINTRE Aurelien",
    team: "Decathlon CMA CGM Team",
    inCourse: true,
    shirt: "shirts\\2026\\decathlon-cma-cgm-team-2026-n2.png",
  },
  {
    id: 32,
    name: "BOL Cees",
    team: "Decathlon CMA CGM Team",
    inCourse: true,
    shirt: "shirts\\2026\\decathlon-cma-cgm-team-2026-n2.png",
  },
  {
    id: 33,
    name: "HEALY Ben",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\2026\\ef-education-easypost-2026-n2.png",
  },
  {
    id: 34,
    name: "ASGREEN Kasper",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\2026\\ef-education-easypost-2026-n2.png",
  },
  {
    id: 35,
    name: "CARAPAZ Richard",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\2026\\ef-education-easypost-2026-n2.png",
  },
  {
    id: 36,
    name: "BAUDIN Alex",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\2026\\ef-education-easypost-2026-n2.png",
  },
  {
    id: 37,
    name: "QUINN Sean",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\2026\\ef-education-easypost-2026-n2.png",
  },
  {
    id: 38,
    name: "STEINHAUSER Georg",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\2026\\ef-education-easypost-2026-n2.png",
  },
  {
    id: 39,
    name: "WALKER Max",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\2026\\ef-education-easypost-2026-n2.png",
  },
  {
    id: 40,
    name: "VALGREN Michael",
    team: "EF Education - EasyPost",
    inCourse: true,
    shirt: "shirts\\2026\\ef-education-easypost-2026-n2.png",
  },
  {
    id: 41,
    name: "MARTIN Guillaume",
    team: "Groupama - FDJ United",
    inCourse: true,
    shirt: "shirts\\2026\\groupama-fdj-united-2026.png",
  },
  {
    id: 42,
    name: "GREGOIRE Romain",
    team: "Groupama - FDJ United",
    inCourse: true,
    shirt: "shirts\\2026\\groupama-fdj-united-2026.png",
  },
  {
    id: 43,
    name: "BERTHET Clement",
    team: "Groupama - FDJ United",
    inCourse: true,
    shirt: "shirts\\2026\\groupama-fdj-united-2026.png",
  },
  {
    id: 44,
    name: "BRAZ AFONSO Clement",
    team: "Groupama - FDJ United",
    inCourse: true,
    shirt: "shirts\\2026\\groupama-fdj-united-2026.png",
  },
  {
    id: 45,
    name: "GERMANI Lorenzo",
    team: "Groupama - FDJ United",
    inCourse: true,
    shirt: "shirts\\2026\\groupama-fdj-united-2026.png",
  },
  {
    id: 46,
    name: "PACHER Quentin",
    team: "Groupama - FDJ United",
    inCourse: true,
    shirt: "shirts\\2026\\groupama-fdj-united-2026.png",
  },
  {
    id: 47,
    name: "RUSSO Clement",
    team: "Groupama - FDJ United",
    inCourse: true,
    shirt: "shirts\\2026\\groupama-fdj-united-2026.png",
  },
  {
    id: 48,
    name: "COSTIOU Ewen",
    team: "Groupama - FDJ United",
    inCourse: true,
    shirt: "shirts\\2026\\groupama-fdj-united-2026.png",
  },
  {
    id: 49,
    name: "ARENSMAN Thymen",
    team: "Netcompany INEOS",
    inCourse: true,
    shirt: "shirts\\2026\\ineos-grenadiers-2026-n2.png",
  },
  {
    id: 50,
    name: "BERNAL Egan",
    team: "Netcompany INEOS",
    inCourse: true,
    shirt: "shirts\\2026\\ineos-grenadiers-2026-n2.png",
  },
  {
    id: 51,
    name: "FOSS Tobias",
    team: "Netcompany INEOS",
    inCourse: true,
    shirt: "shirts\\2026\\ineos-grenadiers-2026-n2.png",
  },
  {
    id: 52,
    name: "GANNA Filippo",
    team: "Netcompany INEOS",
    inCourse: true,
    shirt: "shirts\\2026\\ineos-grenadiers-2026-n2.png",
  },
  {
    id: 53,
    name: "GODON Dorian",
    team: "Netcompany INEOS",
    inCourse: true,
    shirt: "shirts\\2026\\ineos-grenadiers-2026-n2.png",
  },
  {
    id: 54,
    name: "KWIATKOWSKI Michal",
    team: "Netcompany INEOS",
    inCourse: true,
    shirt: "shirts\\2026\\ineos-grenadiers-2026-n2.png",
  },
  {
    id: 55,
    name: "TARLING Joshua",
    team: "Netcompany INEOS",
    inCourse: true,
    shirt: "shirts\\2026\\ineos-grenadiers-2026-n2.png",
  },
  {
    id: 56,
    name: "VAUQUELIN Kevin",
    team: "Netcompany INEOS",
    inCourse: true,
    shirt: "shirts\\2026\\ineos-grenadiers-2026-n2.png",
  },
  {
    id: 57,
    name: "AYUSO Juan",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\2026\\lidl-trek-2026.png",
  },
  {
    id: 58,
    name: "PEDERSEN Mads",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\2026\\lidl-trek-2026.png",
  },
  {
    id: 59,
    name: "VACEK Mathias",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\2026\\lidl-trek-2026.png",
  },
  {
    id: 60,
    name: "SKJELMOSE Mattias",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\2026\\lidl-trek-2026.png",
  },
  {
    id: 61,
    name: "SIMMONS Quinn",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\2026\\lidl-trek-2026.png",
  },
  {
    id: 62,
    name: "GEE-WEST Derek",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\2026\\lidl-trek-2026.png",
  },
  {
    id: 63,
    name: "VERONA Carlos",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\2026\\lidl-trek-2026.png",
  },
  {
    id: 64,
    name: "SKUJINS Toms",
    team: "Lidl - Trek",
    inCourse: true,
    shirt: "shirts\\2026\\lidl-trek-2026.png",
  },
  {
    id: 65,
    name: "DE LIE Arnaud",
    team: "Lotto Intermarché",
    inCourse: true,
    shirt: "shirts\\2026\\lotto-intermarche-2026-n2.png",
  },
  {
    id: 66,
    name: "VAN EETVELT Lennert",
    team: "Lotto Intermarché",
    inCourse: true,
    shirt: "shirts\\2026\\lotto-intermarche-2026-n2.png",
  },
  {
    id: 67,
    name: "ZIMMERMANN Georg",
    team: "Lotto Intermarché",
    inCourse: true,
    shirt: "shirts\\2026\\lotto-intermarche-2026-n2.png",
  },
  {
    id: 68,
    name: "ARTZ Huub",
    team: "Lotto Intermarché",
    inCourse: true,
    shirt: "shirts\\2026\\lotto-intermarche-2026-n2.png",
  },
  {
    id: 69,
    name: "BERCKMOES Jenno",
    team: "Lotto Intermarché",
    inCourse: true,
    shirt: "shirts\\2026\\lotto-intermarche-2026-n2.png",
  },
  {
    id: 70,
    name: "SLOCK Liam",
    team: "Lotto Intermarché",
    inCourse: true,
    shirt: "shirts\\2026\\lotto-intermarche-2026-n2.png",
  },
  {
    id: 71,
    name: "CRAPS Lars",
    team: "Lotto Intermarché",
    inCourse: true,
    shirt: "shirts\\2026\\lotto-intermarche-2026-n2.png",
  },
  {
    id: 72,
    name: "VEISTROFFER Baptiste",
    team: "Lotto Intermarché",
    inCourse: true,
    shirt: "shirts\\2026\\lotto-intermarche-2026-n2.png",
  },
  {
    id: 73,
    name: "UIJTDEBROEKS Cian",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\2026\\movistar-team-2026-n2.png",
  },
  {
    id: 74,
    name: "GARCIA PIERNA Raul",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\2026\\movistar-team-2026-n2.png",
  },
  {
    id: 75,
    name: "CASTRILLO Pablo",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\2026\\movistar-team-2026-n2.png",
  },
  {
    id: 76,
    name: "RUBIO Einer",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\2026\\movistar-team-2026-n2.png",
  },
  {
    id: 77,
    name: "ROMO Javier",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\2026\\movistar-team-2026-n2.png",
  },
  {
    id: 78,
    name: "OLIVEIRA Nelson",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\2026\\movistar-team-2026-n2.png",
  },
  {
    id: 79,
    name: "CEPEDA Jefferson Alveiro",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\2026\\movistar-team-2026-n2.png",
  },
  {
    id: 80,
    name: "HESSMANN Michel",
    team: "Movistar Team",
    inCourse: true,
    shirt: "shirts\\2026\\movistar-team-2026-n2.png",
  },
  {
    id: 81,
    name: "GIRMAY Biniam",
    team: "NSN Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\nsn-cycling-team-2026.png",
  },
  {
    id: 82,
    name: "STEWART Jake",
    team: "NSN Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\nsn-cycling-team-2026.png",
  },
  {
    id: 83,
    name: "ASKEY Lewis",
    team: "NSN Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\nsn-cycling-team-2026.png",
  },
  {
    id: 84,
    name: "NEILANDS Krists",
    team: "NSN Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\nsn-cycling-team-2026.png",
  },
  {
    id: 85,
    name: "FRIGO Marco",
    team: "NSN Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\nsn-cycling-team-2026.png",
  },
  {
    id: 86,
    name: "LOUVEL Matis",
    team: "NSN Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\nsn-cycling-team-2026.png",
  },
  {
    id: 87,
    name: "BENNETT George",
    team: "NSN Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\nsn-cycling-team-2026.png",
  },
  {
    id: 88,
    name: "VAN ASBROECK Tom",
    team: "NSN Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\nsn-cycling-team-2026.png",
  },
  {
    id: 89,
    name: "VAN DIJKE Tim",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\2026\\red-bull-bora-hansgrohe-2026.png",
  },
  {
    id: 90,
    name: "EVENEPOEL Remco",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\2026\\red-bull-bora-hansgrohe-2026.png",
  },
  {
    id: 91,
    name: "DENZ Nico",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\2026\\red-bull-bora-hansgrohe-2026.png",
  },
  {
    id: 92,
    name: "LIPOWITZ Florian",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\2026\\red-bull-bora-hansgrohe-2026.png",
  },
  {
    id: 93,
    name: "CATTANEO Mattia",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\2026\\red-bull-bora-hansgrohe-2026.png",
  },
  {
    id: 94,
    name: "TRATNIK Jan",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\2026\\red-bull-bora-hansgrohe-2026.png",
  },
  {
    id: 95,
    name: "VAN GILS Maxim",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\2026\\red-bull-bora-hansgrohe-2026.png",
  },
  {
    id: 96,
    name: "HINDLEY Jai",
    team: "Red Bull - BORA - hansgrohe",
    inCourse: true,
    shirt: "shirts\\2026\\red-bull-bora-hansgrohe-2026.png",
  },
  {
    id: 97,
    name: "PARET-PEINTRE Valentin",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\2026\\soudal-quick-step-2026.png",
  },
  {
    id: 98,
    name: "MERLIER Tim",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\2026\\soudal-quick-step-2026.png",
  },
  {
    id: 99,
    name: "EENKHOORN Pascal",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\2026\\soudal-quick-step-2026.png",
  },
  {
    id: 100,
    name: "STUYVEN Jasper",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\2026\\soudal-quick-step-2026.png",
  },
  {
    id: 101,
    name: "VAN BAARLE Dylan",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\2026\\soudal-quick-step-2026.png",
  },
  {
    id: 102,
    name: "VAN LERBERGHE Bert",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\2026\\soudal-quick-step-2026.png",
  },
  {
    id: 103,
    name: "VAN WILDER Ilan",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\2026\\soudal-quick-step-2026.png",
  },
  {
    id: 104,
    name: "VERVAEKE Louis",
    team: "Soudal Quick-Step",
    inCourse: true,
    shirt: "shirts\\2026\\soudal-quick-step-2026.png",
  },
  {
    id: 105,
    name: "MATTHEWS Michael",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\2026",
  },
  {
    id: 106,
    name: "PLAPP Luke",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\2026\\team-jayco-alula-2026-n2.png",
  },
  {
    id: 107,
    name: "ACKERMANN Pascal",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\2026\\team-jayco-alula-2026-n2.png",
  },
  {
    id: 108,
    name: "O'CONNOR Ben",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\2026\\team-jayco-alula-2026-n2.png",
  },
  {
    id: 109,
    name: "SCHMID Mauro",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\2026\\team-jayco-alula-2026-n2.png",
  },
  {
    id: 110,
    name: "O'BRIEN Kelland",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\2026\\team-jayco-alula-2026-n2.png",
  },
  {
    id: 111,
    name: "ENGELHARDT Felix",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\2026\\team-jayco-alula-2026-n2.png",
  },
  {
    id: 112,
    name: "DURBRIDGE Luke",
    team: "Team Jayco AlUla",
    inCourse: true,
    shirt: "shirts\\2026\\team-jayco-alula-2026-n2.png",
  },
  {
    id: 113,
    name: "BITTNER Pavel",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\2026\\team-picnic-postnl-2026-n2.png",
  },
  {
    id: 114,
    name: "BARGUIL Warren",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\2026\\team-picnic-postnl-2026-n2.png",
  },
  {
    id: 115,
    name: "VAN DEN BROEK Frank",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\2026\\team-picnic-postnl-2026-n2.png",
  },
  {
    id: 116,
    name: "DHONDT Robbe",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\2026\\team-picnic-postnl-2026-n2.png",
  },
  {
    id: 117,
    name: "VAN DEN BERG Julius",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\2026\\team-picnic-postnl-2026-n2.png",
  },
  {
    id: 118,
    name: "MARKL Niklas",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\2026\\team-picnic-postnl-2026-n2.png",
  },
  {
    id: 119,
    name: "BIESTERBOS Frits",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\2026\\team-picnic-postnl-2026-n2.png",
  },
  {
    id: 120,
    name: "DEGENKOLB John",
    team: "Team Picnic PostNL",
    inCourse: true,
    shirt: "shirts\\2026\\team-picnic-postnl-2026-n2.png",
  },
  {
    id: 121,
    name: "CAMPENAERTS Victor",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\2026\\team-visma-lease-a-bike-2026-n3.png",
  },
  {
    id: 122,
    name: "AFFINI Edoardo",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\2026\\team-visma-lease-a-bike-2026-n3.png",
  },
  {
    id: 123,
    name: "HAGENES Per Strand",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\2026\\team-visma-lease-a-bike-2026-n3.png",
  },
  {
    id: 124,
    name: "JORGENSON Matteo",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\2026\\team-visma-lease-a-bike-2026-n3.png",
  },
  {
    id: 125,
    name: "KUSS Sepp",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\2026\\team-visma-lease-a-bike-2026-n3.png",
  },
  {
    id: 126,
    name: "ARMIRAIL Bruno",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\2026\\team-visma-lease-a-bike-2026-n3.png",
  },
  {
    id: 127,
    name: "PIGANZOLI Davide",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\2026\\team-visma-lease-a-bike-2026-n3.png",
  },
  {
    id: 128,
    name: "VINGEGAARD Jonas",
    team: "Team Visma | Lease a Bike",
    inCourse: true,
    shirt: "shirts\\2026\\team-visma-lease-a-bike-2026-n3.png",
  },
  {
    id: 129,
    name: "CORT Magnus",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\2026\\uno-x-mobility-2026-n2.png",
  },
  {
    id: 130,
    name: "JOHANNESSEN Tobias Halland",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\2026\\uno-x-mobility-2026-n2.png",
  },
  {
    id: 131,
    name: "SKAARSETH Anders",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\2026\\uno-x-mobility-2026-n2.png",
  },
  {
    id: 132,
    name: "WAERENSKJOLD Soren",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\2026\\uno-x-mobility-2026-n2.png",
  },
  {
    id: 133,
    name: "CHARMIG Anthon",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\2026\\uno-x-mobility-2026-n2.png",
  },
  {
    id: 134,
    name: "ABRAHAMSEN Jonas",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\2026\\uno-x-mobility-2026-n2.png",
  },
  {
    id: 135,
    name: "TRAEEN Torstein",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\2026\\uno-x-mobility-2026-n2.png",
  },
  {
    id: 136,
    name: "JOHANNESSEN Anders Halland",
    team: "Uno-X Mobility",
    inCourse: true,
    shirt: "shirts\\2026\\uno-x-mobility-2026-n2.png",
  },
  {
    id: 137,
    name: "TEUNISSEN Mike",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\2026\\xds-astana-team-2026-n2.png",
  },
  {
    id: 138,
    name: "HIGUITA Sergio",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\2026\\xds-astana-team-2026-n2.png",
  },
  {
    id: 139,
    name: "TEJADA Harold",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\2026\\xds-astana-team-2026-n2.png",
  },
  {
    id: 140,
    name: "KANTER Max",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\2026\\xds-astana-team-2026-n2.png",
  },
  {
    id: 141,
    name: "VINOKUROV Nicolas",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\2026\\xds-astana-team-2026-n2.png",
  },
  {
    id: 142,
    name: "BALLERINI Davide",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\2026\\xds-astana-team-2026-n2.png",
  },
  {
    id: 143,
    name: "GATE Aaron",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\2026\\xds-astana-team-2026-n2.png",
  },
  {
    id: 144,
    name: "VELASCO Simone",
    team: "XDS Astana Team",
    inCourse: true,
    shirt: "shirts\\2026\\xds-astana-team-2026-n2.png",
  },
  {
    id: 145,
    name: "ALLEGAERT Piet",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\2026\\cofidis-2026-n2.png",
  },
  {
    id: 146,
    name: "BIERMANS Jenthe",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\2026\\cofidis-2026-n2.png",
  },
  {
    id: 147,
    name: "FRETIN Milan",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\2026\\cofidis-2026-n2.png",
  },
  {
    id: 148,
    name: "KIRSCH Alex",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\2026\\cofidis-2026-n2.png",
  },
  {
    id: 149,
    name: "PAGE Hugo",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\2026\\cofidis-2026-n2.png",
  },
  {
    id: 150,
    name: "ARANBURU Alex",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\2026\\cofidis-2026-n2.png",
  },
  {
    id: 151,
    name: "THOMAS Benjamin",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\2026\\cofidis-2026-n2.png",
  },
  {
    id: 152,
    name: "IZAGIRRE Ion",
    team: "Cofidis",
    inCourse: true,
    shirt: "shirts\\2026\\cofidis-2026-n2.png",
  },
  {
    id: 153,
    name: "ALAPHILIPPE Julian",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\tudor-pro-cycling-team-2026.png",
  },
  {
    id: 154,
    name: "TRENTIN Matteo",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\tudor-pro-cycling-team-2026.png",
  },
  {
    id: 155,
    name: "STORER Michael",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\tudor-pro-cycling-team-2026.png",
  },
  {
    id: 156,
    name: "PLUIMERS Rick",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\tudor-pro-cycling-team-2026.png",
  },
  {
    id: 157,
    name: "DE KLEIJN Arvid",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\tudor-pro-cycling-team-2026.png",
  },
  {
    id: 158,
    name: "HALLER Marco",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\tudor-pro-cycling-team-2026.png",
  },
  {
    id: 159,
    name: "HIRSCHI Marc",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\tudor-pro-cycling-team-2026.png",
  },
  {
    id: 160,
    name: "VOISARD Yannis",
    team: "Tudor Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\tudor-pro-cycling-team-2026.png",
  },
  {
    id: 161,
    name: "JEGAT Jordan",
    team: "TotalEnergies",
    inCourse: true,
    shirt: "shirts\\2026\\team-totalenergies-2026.png",
  },
  {
    id: 162,
    name: "DELETTRE Alexandre",
    team: "TotalEnergies",
    inCourse: true,
    shirt: "shirts\\2026\\team-totalenergies-2026.png",
  },
  {
    id: 163,
    name: "TURGIS Anthony",
    team: "TotalEnergies",
    inCourse: true,
    shirt: "shirts\\2026\\team-totalenergies-2026.png",
  },
  {
    id: 164,
    name: "VERCHER Matteo",
    team: "TotalEnergies",
    inCourse: true,
    shirt: "shirts\\2026\\team-totalenergies-2026.png",
  },
  {
    id: 165,
    name: "LE BERRE Mathis",
    team: "TotalEnergies",
    inCourse: true,
    shirt: "shirts\\2026\\team-totalenergies-2026.png",
  },
  {
    id: 166,
    name: "BREUILLARD Nicolas",
    team: "TotalEnergies",
    inCourse: true,
    shirt: "shirts\\2026\\team-totalenergies-2026.png",
  },
  {
    id: 167,
    name: "DELBOVE Joris",
    team: "TotalEnergies",
    inCourse: true,
    shirt: "shirts\\2026\\team-totalenergies-2026.png",
  },
  {
    id: 168,
    name: "GUERNALEC Thibault",
    team: "TotalEnergies",
    inCourse: true,
    shirt: "shirts\\2026\\team-totalenergies-2026.png",
  },
  {
    id: 169,
    name: "MOLENAAR Alex",
    team: "Caja Rural - Seguros RGA",
    inCourse: true,
    shirt: "shirts\\2026\\caja-rural-seguros-rga-2026-n3.png",
  },
  {
    id: 170,
    name: "NICOLAU Joel",
    team: "Caja Rural - Seguros RGA",
    inCourse: true,
    shirt: "shirts\\2026\\caja-rural-seguros-rga-2026-n3.png",
  },
  {
    id: 171,
    name: "BALDERSTONE Abel",
    team: "Caja Rural - Seguros RGA",
    inCourse: true,
    shirt: "shirts\\2026\\caja-rural-seguros-rga-2026-n3.png",
  },
  {
    id: 172,
    name: "BERWICK Sebastian",
    team: "Caja Rural - Seguros RGA",
    inCourse: true,
    shirt: "shirts\\2026\\caja-rural-seguros-rga-2026-n3.png",
  },
  {
    id: 173,
    name: "GAVIRIA Fernando",
    team: "Caja Rural - Seguros RGA",
    inCourse: true,
    shirt: "shirts\\2026\\caja-rural-seguros-rga-2026-n3.png",
  },
  {
    id: 174,
    name: "OLDANI Stefano",
    team: "Caja Rural - Seguros RGA",
    inCourse: true,
    shirt: "shirts\\2026\\caja-rural-seguros-rga-2026-n3.png",
  },
  {
    id: 175,
    name: "OTRUBA Jakub",
    team: "Caja Rural - Seguros RGA",
    inCourse: true,
    shirt: "shirts\\2026\\caja-rural-seguros-rga-2026-n3.png",
  },
  {
    id: 176,
    name: "PARRA Jose Felix",
    team: "Caja Rural - Seguros RGA",
    inCourse: true,
    shirt: "shirts\\2026\\caja-rural-seguros-rga-2026-n3.png",
  },
  {
    id: 177,
    name: "PIDCOCK Tom",
    team: "Pinarello Q36.5 Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\pinarello-q365-pro-cycling-team-2026.png",
  },
  {
    id: 178,
    name: "AZPARREN Xabier Mikel",
    team: "Pinarello Q36.5 Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\pinarello-q365-pro-cycling-team-2026.png",
  },
  {
    id: 179,
    name: "HARPER Chris",
    team: "Pinarello Q36.5 Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\pinarello-q365-pro-cycling-team-2026.png",
  },
  {
    id: 180,
    name: "HERMANS Quinten",
    team: "Pinarello Q36.5 Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\pinarello-q365-pro-cycling-team-2026.png",
  },
  {
    id: 181,
    name: "HOWSON Damien",
    team: "Pinarello Q36.5 Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\pinarello-q365-pro-cycling-team-2026.png",
  },
  {
    id: 182,
    name: "MEURISSE Xandro",
    team: "Pinarello Q36.5 Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\pinarello-q365-pro-cycling-team-2026.png",
  },
  {
    id: 183,
    name: "VAN MOER Brent",
    team: "Pinarello Q36.5 Pro Cycling Team",
    inCourse: true,
    shirt: "shirts\\2026\\pinarello-q365-pro-cycling-team-2026.png",
  },
];
